name: Azure Function App CI/CD

on:
  push:
    branches:
      - main  # Trigger workflow on changes to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify the Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Deploy to Azure Function App
      - name: Deploy to Azure
        uses: azure/functions-action@v1
        with:
          app-name: devopsmyprojectpractice  # Replace with your Function App name
          package: '.'
