name: Azure Function App CI/CD

on:
  push:
    branches:
      - main  # Trigger workflow on changes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # Reference to the stored JSON credentials

      # Step 3: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Deploy to Azure Function App
      - name: Deploy to Azure
        uses: azure/functions-action@v1
        with:
          app-name: devopsmyprojectpractice  # Replace with your Function App name
          package: '.'
